name: Deploy

on:
  push:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
  SLACK_METRICS_CHANNEL_ID: ${{ secrets.SLACK_METRICS_CHANNEL_ID }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm ci

      - name: Deploy
        run: npm run deploy

      - uses: homoluctus/slatify@v2.1.2
        if: always()
        with:
          type: ${{ job.status }}
          job_name: ":penguin: *${{ github.workflow }}*"
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
